export enum ActionType {
  SEARCH_REPOSITORIES_REQUEST = 'SEARCH_REPOSITORIES_REQUEST',
  SEARCH_REPOSITORIES_SUCCESS = 'SEARCH_REPOSITORIES_SUCCESS',
  SEARCH_REPOSITORIES_ERROR = 'SEARCH_REPOSITORIES_ERROR'
}
